/**
 * Snapshot chat.subscribe@1.6's exact JSON-Schema surface into the in-tree
 * fixture used by `chat-subscribe-v16-surface-compat.test.ts`.
 *
 *   bun run protocol/scripts/snapshot-chat-subscribe-v16-surface.ts > \
 *     protocol/src/host/agent/gui/__tests__/__fixtures__/chat-subscribe-v16-surface.ts
 *
 * `chat.subscribe@1.6` is a released, frozen line (see `chatSubscribeV16` in
 * `subscribe.ts`) - it must never change again. This fixture was originally
 * captured from the commit immediately before the pre-image freeze
 * (`git -C traycer show <freeze-commit>^`), before `chatSubscribeV16` was
 * rebound from the live schemas to the frozen `chatSchemaPreImage` /
 * `runtimeEventSchemaPreImage`. Regenerating it from the current tree should
 * therefore reproduce the exact same bytes forever; a diff here means the
 * frozen line drifted and must be investigated, not silently re-pinned. A
 * fixture diff can also mean the Zod version changed; confirm the contract is
 * unchanged before regenerating in that case.
 */
import { z } from "zod";
import { chatSubscribeV16 } from "@traycer/protocol/host/agent/gui/subscribe";

const surface = {
  method: chatSubscribeV16.method,
  schemaVersion: chatSubscribeV16.schemaVersion,
  openRequest: {
    storage: z.toJSONSchema(chatSubscribeV16.openRequestSchema, {
      io: "input",
    }),
    domain: z.toJSONSchema(chatSubscribeV16.openRequestSchema),
  },
  serverFrame: {
    storage: z.toJSONSchema(chatSubscribeV16.serverFrameSchema, {
      io: "input",
    }),
    domain: z.toJSONSchema(chatSubscribeV16.serverFrameSchema),
  },
  clientFrame: {
    storage: z.toJSONSchema(chatSubscribeV16.clientFrameSchema, {
      io: "input",
    }),
    domain: z.toJSONSchema(chatSubscribeV16.clientFrameSchema),
  },
};

process.stdout.write(
  "// AUTO-GENERATED by protocol/scripts/snapshot-chat-subscribe-v16-surface.ts - do not edit by hand.\n" +
    "// The exact frozen chat.subscribe@1.6 JSON-Schema surface; pinned by\n" +
    "// chat-subscribe-v16-surface-compat.test.ts so the hand-copied freeze can\n" +
    "// never silently drift.\n" +
    `export const chatSubscribeV16SurfaceBaseline = ${JSON.stringify(surface, null, 2)};\n`,
);
