/**
 * Emits the released `/stream` method-name set. Guard rejects removals; browser namespace is `browser.sessions` and `browser.screencast`.
 * Regenerate only for a coordinated stream baseline change.
 */
import { hostStreamRpcRegistry } from "@traycer/protocol/host/index";

const header =
  "// AUTO-GENERATED by protocol/scripts/snapshot-released-stream-method-names.ts - do not edit by hand.\n" +
  "// Released /stream method-name baseline; frozen by released-stream-surface-compat.test.ts.\n";
const names = Object.keys(hostStreamRpcRegistry).sort();

process.stdout.write(
  `${header}export const releasedStreamMethodNames: readonly string[] = [\n${names
    .map((name) => `  ${JSON.stringify(name)},`)
    .join("\n")}\n];\n`,
);
