/**
 * Emits the released `/rpc` method-name set for the unary host RPC registry -
 * the sorted `Object.keys(hostRpcRegistry)` (the handshake-visible method names,
 * without serializing every method's schemas).
 *
 * The committed snapshot (`src/host/__tests__/__fixtures__/released-method-names.ts`)
 * freezes the handshake-critical method-name set. `released-surface-compat.test.ts`
 * fails if a method name is added or removed - the way `1.0.1-rc.1` broke the
 * handshake against the `1.0.0` host (`worktree.readScriptsAtRef` was a new
 * method name). Per-method schema evolution is intentionally NOT frozen here;
 * schemas grow additively within a version, and breaking changes ride a version
 * bump instead.
 *
 * Regenerate ONLY for a coordinated release that drops support for the baselined
 * host - the resulting diff is the reviewable record of that decision:
 *
 *   bun run protocol/scripts/snapshot-released-method-names.ts > \
 *     protocol/src/host/__tests__/__fixtures__/released-method-names.ts
 */
import { hostRpcRegistry } from "@traycer/protocol/host/index";

const header =
  "// AUTO-GENERATED by protocol/scripts/snapshot-released-method-names.ts - do not edit by hand.\n" +
  "// The host-v1.0.0 /rpc method-name set; frozen by released-surface-compat.test.ts.\n";
const names = Object.keys(hostRpcRegistry).sort();

process.stdout.write(
  `${header}export const releasedMethodNames: readonly string[] = [\n${names
    .map((name) => `  ${JSON.stringify(name)},`)
    .join("\n")}\n];\n`,
);
