/**
 * Emits the released-floor `/rpc` method-name set for the unary host RPC
 * registry. Optional-capability methods declare a `degrade` strategy and are
 * deliberately excluded: adding them to this snapshot would make them part of
 * the handshake-fatal floor.
 *
 * The committed snapshot (`src/host/__tests__/__fixtures__/released-method-names.ts`)
 * freezes the handshake-critical method-name set. `released-surface-compat.test.ts`
 * freezes the handshake-critical released floor. Optional methods never enter
 * it; their missing-peer behavior is declared in the registry. Per-method
 * schema evolution is intentionally NOT frozen here; schemas grow additively
 * within a version, and breaking changes ride a version bump instead.
 *
 * Regenerate ONLY for a coordinated release that drops support for the baselined
 * host - the resulting diff is the reviewable record of that decision:
 *
 *   bun run protocol/scripts/snapshot-released-method-names.ts > \
 *     protocol/src/host/__tests__/__fixtures__/released-method-names.ts
 */
import { hostRpcRegistry } from "@traycer/protocol/host/index";

const header =
  "// AUTO-GENERATED by protocol/scripts/snapshot-released-method-names.ts - do not edit by hand.\n" +
  "// The host-v1.0.0 released-floor /rpc method-name set; optional capabilities are excluded.\n";
const names = Object.entries(hostRpcRegistry)
  .filter(([, registry]) => !Object.hasOwn(registry, "degrade"))
  .map(([method]) => method)
  .sort();

process.stdout.write(
  `${header}export const releasedMethodNames: readonly string[] = [\n${names
    .map((name) => `  ${JSON.stringify(name)},`)
    .join("\n")}\n];\n`,
);
