/**
 * Emits the released `/stream` method-name set for the streaming host RPC
 * registry - the sorted `Object.keys(hostStreamRpcRegistry)` (the
 * handshake-visible method names, without serializing every method's
 * schemas).
 *
 * The unary `/rpc` handshake already has this guard
 * (`snapshot-released-method-names.ts` -> `released-method-names.ts` ->
 * `released-surface-compat.test.ts`). The `/stream` handshake is compat-
 * negotiated the same way (`checkStreamCompatibility` in
 * `@traycer/protocol/framework/stream-compat` is fail-closed on the same
 * method-NAME union as the unary `check()` - a name present on only one
 * peer is a fatal `Incompatible methods` error for the WHOLE `/stream`
 * connection) but had NO equivalent frozen baseline until this file: a
 * future new stream method NAME would sail past the unary guard entirely,
 * even though it breaks the exact same class of handshake.
 *
 * The committed snapshot
 * (`src/host/__tests__/__fixtures__/released-stream-method-names.ts`)
 * freezes the handshake-critical method-name set.
 * `released-stream-surface-compat.test.ts` fails if a method name is added
 * or removed. Per-method schema evolution is intentionally NOT frozen here -
 * schemas grow additively within a version (e.g. `terminal.subscribe` has
 * moved to 1.2, `chat.subscribe` to 1.1 since this baseline, with no new
 * method names); a breaking change rides a version bump instead.
 *
 * Regenerate ONLY for a coordinated release that drops support for the
 * baselined host - the resulting diff is the reviewable record of that
 * decision:
 *
 *   bun run protocol/scripts/snapshot-released-stream-method-names.ts > \
 *     protocol/src/host/__tests__/__fixtures__/released-stream-method-names.ts
 */
import { hostStreamRpcRegistry } from "@traycer/protocol/host/index";

const header =
  "// AUTO-GENERATED by protocol/scripts/snapshot-released-stream-method-names.ts - do not edit by hand.\n" +
  "// The host-v1.0.0 /stream method-name set; frozen by released-stream-surface-compat.test.ts.\n";
const names = Object.keys(hostStreamRpcRegistry).sort();

process.stdout.write(
  `${header}export const releasedStreamMethodNames: readonly string[] = [\n${names
    .map((name) => `  ${JSON.stringify(name)},`)
    .join("\n")}\n];\n`,
);
