/**
 * Emits the released-floor `/rpc` method-name set for the unary host RPC registry.
 * `released-surface-compat.test.ts` freezes the handshake-critical released floor.
 */
import { hostRpcRegistry } from "@traycer/protocol/host/index";

const header =
  "// AUTO-GENERATED by protocol/scripts/snapshot-released-method-names.ts - do not edit by hand.\n" +
  "// The host-v1.0.0 released-floor /rpc method-name set; optional capabilities are excluded.\n";
const names = Object.entries(hostRpcRegistry)
  .filter(([, registry]) => !Object.hasOwn(registry, "degrade"))
  .map(([method]) => method)
  .sort();

process.stdout.write(
  `${header}export const releasedMethodNames: readonly string[] = [\n${names
    .map((name) => `  ${JSON.stringify(name)},`)
    .join("\n")}\n];\n`,
);
