/**
 * Emits the frozen surface of the `chat-head` / `chat-shard` persistence contract: both JSON-Schema IO surfaces of each registered record.
 * Do not edit the generated fixture by hand.
 */
import { getRecordSchema } from "@traycer/protocol/framework/index";
import { chatHeadStorageSchema } from "@traycer/protocol/persistence/chat-sync/head";
import { chatShardStorageSchema } from "@traycer/protocol/persistence/chat-sync/shard";
import { persistenceRecordRegistry } from "@traycer/protocol/persistence/registry";
import { z } from "zod";

const chatHeadSchema = getRecordSchema(
  persistenceRecordRegistry,
  "chat-head",
  "latest",
);

const chatShardSchema = getRecordSchema(
  persistenceRecordRegistry,
  "chat-shard",
  "latest",
);

const header =
  "// AUTO-GENERATED by protocol/scripts/snapshot-chat-sync-schema-surface.ts - do not edit by hand.\n" +
  "// The registered chat-head / chat-shard JSON-Schema surfaces; frozen by chat-sync-schema-surface-compat.test.ts.\n";

const baseline = {
  // The WIRE projections, not the registered schemas' own input surfaces.
  head: {
    storage: z.toJSONSchema(chatHeadStorageSchema, { io: "input" }),
    domain: z.toJSONSchema(chatHeadSchema),
  },
  shard: {
    storage: z.toJSONSchema(chatShardStorageSchema, { io: "input" }),
    domain: z.toJSONSchema(chatShardSchema),
  },
};

process.stdout.write(
  `${header}export const chatSyncSchemaSurfaceBaseline = ${JSON.stringify(baseline, null, 2)};\n`,
);
