/**
 * Emits the released wire-surface baseline for the unary host RPC registry: every
 * method's per-`(major, minor)` request/response JSON-schema fingerprint, as
 * produced by `toJsonSchemas`.
 *
 * The committed baseline (`src/host/__tests__/__fixtures__/released-surface.baseline.ts`)
 * freezes the shipped `/rpc` handshake surface. `released-surface-compat.test.ts`
 * fails if a method name is added or removed, or if any shipped `(method, major,
 * minor)` fingerprint changes in place - the exact two ways 1.0.1-rc.1 broke
 * compatibility with the 1.0.0 host. Additive evolution (a NEW `(major, minor)`
 * of an existing method) is allowed and is not recorded against the baseline.
 *
 * Regenerate ONLY when intentionally shipping a coordinated breaking change that
 * drops support for older peers - the resulting baseline diff is the reviewable
 * record of that decision:
 *
 *   bun run protocol/scripts/snapshot-released-surface.ts > \
 *     protocol/src/host/__tests__/__fixtures__/released-surface.baseline.ts
 */
import { toJsonSchemas } from "@traycer/protocol/framework/index";
import { hostRpcRegistry } from "@traycer/protocol/host/index";

// Emitted as a `.ts` module (not `.json`) so consumers that compile protocol
// sources wholesale - e.g. cloud-ui-v2's `composite` tsconfig includes
// `../traycer/protocol/src` - pick the fixture up through their normal `.ts`
// include glob instead of needing the asset listed explicitly (TS6307).
const header =
  "// AUTO-GENERATED by protocol/scripts/snapshot-released-surface.ts - do not edit by hand.\n" +
  "// Frozen snapshot of the host-v1.0.0 /rpc wire surface; see released-surface-compat.test.ts.\n";

process.stdout.write(
  `${header}export const releasedSurfaceBaseline = ${JSON.stringify(
    toJsonSchemas(hostRpcRegistry),
    null,
    2,
  )};\n`,
);
