/**
 * Emits the frozen surface of the `chat-head` / `chat-shard` persistence
 * contract: both JSON-Schema IO surfaces of each registered record. The two
 * ride one fixture because they are one contract on one version line - a head
 * names shards, a shard embeds the sub-schemas the head's core is built from,
 * and every change that moves one moves the other.
 *
 * Do not edit the generated fixture by hand. When the guard fails, classify the
 * change using `src/persistence/COMPATIBILITY.md` ("Chat-sync contract").
 * Regenerate only after a compatible change has been reviewed or the required
 * breaking-version and migration work is in place:
 *
 *   bun run protocol/scripts/snapshot-chat-sync-schema-surface.ts > \
 *     protocol/src/persistence/chat-sync/__tests__/__fixtures__/chat-sync-schema-surface.ts
 */
import { getRecordSchema } from "@traycer/protocol/framework/index";
import { chatHeadStorageSchema } from "@traycer/protocol/persistence/chat-sync/head";
import { chatShardStorageSchema } from "@traycer/protocol/persistence/chat-sync/shard";
import { persistenceRecordRegistry } from "@traycer/protocol/persistence/registry";
import { z } from "zod";

const chatHeadSchema = getRecordSchema(
  persistenceRecordRegistry,
  "chat-head",
  "latest",
);

const chatShardSchema = getRecordSchema(
  persistenceRecordRegistry,
  "chat-shard",
  "latest",
);

const header =
  "// AUTO-GENERATED by protocol/scripts/snapshot-chat-sync-schema-surface.ts - do not edit by hand.\n" +
  "// The registered chat-head / chat-shard JSON-Schema surfaces; frozen by chat-sync-schema-surface-compat.test.ts.\n";

const baseline = {
  // The WIRE projections, not the registered schemas' own input surfaces. Both
  // records capture unmodeled keys through `z.preprocess`, and
  // `z.toJSONSchema` reports a preprocess's inner (post-capture) schema in both
  // IO modes - which would freeze a "storage" surface requiring the internal
  // `residual` key and marking `core` optional. See `chat-sync/residual.ts`.
  head: {
    storage: z.toJSONSchema(chatHeadStorageSchema, { io: "input" }),
    domain: z.toJSONSchema(chatHeadSchema),
  },
  shard: {
    storage: z.toJSONSchema(chatShardStorageSchema, { io: "input" }),
    domain: z.toJSONSchema(chatShardSchema),
  },
};

process.stdout.write(
  `${header}export const chatSyncSchemaSurfaceBaseline = ${JSON.stringify(baseline, null, 2)};\n`,
);
