/**
 * Emits both JSON-Schema IO surfaces of the registered epic persistence
 * contract. The committed result is a review gate for changes to top-level
 * fields, chats, artifacts, deleted artifacts, and TUI agents.
 *
 * Do not edit the generated fixture by hand. When the guard fails, classify the
 * change using `src/persistence/COMPATIBILITY.md`. Regenerate only after a
 * compatible change has been reviewed or the required breaking-version and
 * migration work is in place:
 *
 *   bun run protocol/scripts/snapshot-epic-schema-surface.ts > \
 *     protocol/src/persistence/epic/__tests__/__fixtures__/epic-schema-surface.ts
 */
import { getRecordSchema } from "@traycer/protocol/framework/index";
import { persistenceRecordRegistry } from "@traycer/protocol/persistence/registry";
import { z } from "zod";

const epicSchema = getRecordSchema(persistenceRecordRegistry, "epic", "latest");

const header =
  "// AUTO-GENERATED by protocol/scripts/snapshot-epic-schema-surface.ts - do not edit by hand.\n" +
  "// The registered epicSchema JSON-Schema surface; frozen by epic-schema-surface-compat.test.ts.\n";

const baseline = {
  storage: z.toJSONSchema(epicSchema, { io: "input" }),
  domain: z.toJSONSchema(epicSchema),
};

process.stdout.write(
  `${header}export const epicSchemaSurfaceBaseline = ${JSON.stringify(baseline, null, 2)};\n`,
);
