/**
 * Emits the JSON-Schema surface of the persisted `chatSchema`, in BOTH IO
 * modes: `storage` (`{ io: "input" }`, what's actually written to the Yjs
 * doc) and `domain` (default/output mode, what every in-memory/wire consumer
 * sees).
 *
 * The committed snapshot
 * (`src/persistence/epic/__tests__/__fixtures__/chat-schema-surface.ts`)
 * freezes this surface. `chat-schema-surface-compat.test.ts` fails on ANY
 * change - additive or not - because a shipped v1.1.x host's
 * `chatSchema.safeParse` is fail-closed on the WHOLE surface: a new enum
 * value or discriminated-union variant anywhere in the tree makes the entire
 * persisted chat unreadable (`CHAT_INVALID`), the way the ScheduleWakeup
 * change did by widening `autonomousResumeTriggerSchema.kind`. Only a new
 * defaulted/nullable key is safe for a shipped host to receive.
 *
 * Regenerate ONLY after confirming the change is one of:
 *   - a new key with `.default(...)` / `.nullable()` (the safe pattern), or
 *   - a deliberate compat break gated by a persisted `schemaVersion` bump.
 * The diff against this baseline is the reviewable record of that decision.
 *
 *   bun run protocol/scripts/snapshot-chat-schema-surface.ts > \
 *     protocol/src/persistence/epic/__tests__/__fixtures__/chat-schema-surface.ts
 */
import { chatSchema } from "@traycer/protocol/persistence/epic/chat";
import { z } from "zod";

const header =
  "// AUTO-GENERATED by protocol/scripts/snapshot-chat-schema-surface.ts - do not edit by hand.\n" +
  "// The persisted chatSchema JSON-Schema surface; frozen by chat-schema-surface-compat.test.ts.\n";

const baseline = {
  storage: z.toJSONSchema(chatSchema, { io: "input" }),
  domain: z.toJSONSchema(chatSchema),
};

process.stdout.write(
  `${header}export const chatSchemaSurfaceBaseline = ${JSON.stringify(baseline, null, 2)};\n`,
);
