import { writeFileSync } from "node:fs";
import { baseThemeColors } from "../src/lib/themes/builtin-palettes";

// Keep the pre-module CSS palette in sync with the runtime palette registry.
const declarations = Object.entries(baseThemeColors.light).map(
  ([token, light]) => {
    const dark = Object.entries(baseThemeColors.dark).find(
      ([name]) => name === token,
    )?.[1];
    return `  --${token}: ${light === dark ? light : `light-dark(${light}, ${dark ?? light})`};`;
  },
);
const baseDarkDeclarations = Object.entries({
  ...baseThemeColors.light,
  ...baseThemeColors.dark,
}).map(([token, value]) => `  --${token}: ${value};`);
writeFileSync(
  new URL("../src/styles/theme-fallback.css", import.meta.url),
  [
    "/* Generated by bun scripts/generate-theme-fallback.ts. Do not edit directly. */",
    ":root {",
    "  color-scheme: light dark;",
    ...Object.entries(baseThemeColors.light).map(
      ([token, value]) => `  --${token}: ${value};`,
    ),
    "}",
    "@supports (color: light-dark(white, black)) {",
    "  :root {",
    ...declarations.map((declaration) => `  ${declaration}`),
    "  }",
    "}",
    ":root.light {",
    "  color-scheme: light;",
    "}",
    ":root.dark {",
    "  color-scheme: dark;",
    "}",
    "/* A subtree painted on a fixed dark ground, whatever theme is active: the",
    "   base dark palette, declared on the element so it outranks the tokens the",
    "   theme applier writes on <html>, and the `dark:` variant follows it. */",
    "@utility theme-base-dark {",
    "  color-scheme: dark;",
    ...baseDarkDeclarations,
    "}",
    "",
  ].join("\n"),
);
