/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as SettingsRouteImport } from "./routes/settings";
import { Route as OnboardingRouteImport } from "./routes/onboarding";
import { Route as EpicsRouteImport } from "./routes/epics";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as SettingsIndexRouteImport } from "./routes/settings.index";
import { Route as EpicsIndexRouteImport } from "./routes/epics/index";
import { Route as SettingsWorktreesRouteImport } from "./routes/settings.worktrees";
import { Route as SettingsShellRouteImport } from "./routes/settings.shell";
import { Route as SettingsServiceRouteImport } from "./routes/settings.service";
import { Route as SettingsProvidersRouteImport } from "./routes/settings.providers";
import { Route as SettingsKeybindingsRouteImport } from "./routes/settings.keybindings";
import { Route as SettingsHostRouteImport } from "./routes/settings.host";
import { Route as SettingsGeneralRouteImport } from "./routes/settings.general";
import { Route as SettingsAppearanceRouteImport } from "./routes/settings.appearance";
import { Route as DraftNewRouteImport } from "./routes/draft.new";
import { Route as DraftDraftIdRouteImport } from "./routes/draft.$draftId";
import { Route as EpicsEpicIdTabIdRouteImport } from "./routes/epics.$epicId.$tabId";

const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any);
const OnboardingRoute = OnboardingRouteImport.update({
  id: "/onboarding",
  path: "/onboarding",
  getParentRoute: () => rootRouteImport,
} as any);
const EpicsRoute = EpicsRouteImport.update({
  id: "/epics",
  path: "/epics",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => SettingsRoute,
} as any);
const EpicsIndexRoute = EpicsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => EpicsRoute,
} as any);
const SettingsWorktreesRoute = SettingsWorktreesRouteImport.update({
  id: "/worktrees",
  path: "/worktrees",
  getParentRoute: () => SettingsRoute,
} as any);
const SettingsShellRoute = SettingsShellRouteImport.update({
  id: "/shell",
  path: "/shell",
  getParentRoute: () => SettingsRoute,
} as any);
const SettingsServiceRoute = SettingsServiceRouteImport.update({
  id: "/service",
  path: "/service",
  getParentRoute: () => SettingsRoute,
} as any);
const SettingsProvidersRoute = SettingsProvidersRouteImport.update({
  id: "/providers",
  path: "/providers",
  getParentRoute: () => SettingsRoute,
} as any);
const SettingsKeybindingsRoute = SettingsKeybindingsRouteImport.update({
  id: "/keybindings",
  path: "/keybindings",
  getParentRoute: () => SettingsRoute,
} as any);
const SettingsHostRoute = SettingsHostRouteImport.update({
  id: "/host",
  path: "/host",
  getParentRoute: () => SettingsRoute,
} as any);
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: "/general",
  path: "/general",
  getParentRoute: () => SettingsRoute,
} as any);
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: "/appearance",
  path: "/appearance",
  getParentRoute: () => SettingsRoute,
} as any);
const DraftNewRoute = DraftNewRouteImport.update({
  id: "/draft/new",
  path: "/draft/new",
  getParentRoute: () => rootRouteImport,
} as any);
const DraftDraftIdRoute = DraftDraftIdRouteImport.update({
  id: "/draft/$draftId",
  path: "/draft/$draftId",
  getParentRoute: () => rootRouteImport,
} as any);
const EpicsEpicIdTabIdRoute = EpicsEpicIdTabIdRouteImport.update({
  id: "/$epicId/$tabId",
  path: "/$epicId/$tabId",
  getParentRoute: () => EpicsRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/epics": typeof EpicsRouteWithChildren;
  "/onboarding": typeof OnboardingRoute;
  "/settings": typeof SettingsRouteWithChildren;
  "/draft/$draftId": typeof DraftDraftIdRoute;
  "/draft/new": typeof DraftNewRoute;
  "/settings/appearance": typeof SettingsAppearanceRoute;
  "/settings/general": typeof SettingsGeneralRoute;
  "/settings/host": typeof SettingsHostRoute;
  "/settings/keybindings": typeof SettingsKeybindingsRoute;
  "/settings/providers": typeof SettingsProvidersRoute;
  "/settings/service": typeof SettingsServiceRoute;
  "/settings/shell": typeof SettingsShellRoute;
  "/settings/worktrees": typeof SettingsWorktreesRoute;
  "/epics/": typeof EpicsIndexRoute;
  "/settings/": typeof SettingsIndexRoute;
  "/epics/$epicId/$tabId": typeof EpicsEpicIdTabIdRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/onboarding": typeof OnboardingRoute;
  "/draft/$draftId": typeof DraftDraftIdRoute;
  "/draft/new": typeof DraftNewRoute;
  "/settings/appearance": typeof SettingsAppearanceRoute;
  "/settings/general": typeof SettingsGeneralRoute;
  "/settings/host": typeof SettingsHostRoute;
  "/settings/keybindings": typeof SettingsKeybindingsRoute;
  "/settings/providers": typeof SettingsProvidersRoute;
  "/settings/service": typeof SettingsServiceRoute;
  "/settings/shell": typeof SettingsShellRoute;
  "/settings/worktrees": typeof SettingsWorktreesRoute;
  "/epics": typeof EpicsIndexRoute;
  "/settings": typeof SettingsIndexRoute;
  "/epics/$epicId/$tabId": typeof EpicsEpicIdTabIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/epics": typeof EpicsRouteWithChildren;
  "/onboarding": typeof OnboardingRoute;
  "/settings": typeof SettingsRouteWithChildren;
  "/draft/$draftId": typeof DraftDraftIdRoute;
  "/draft/new": typeof DraftNewRoute;
  "/settings/appearance": typeof SettingsAppearanceRoute;
  "/settings/general": typeof SettingsGeneralRoute;
  "/settings/host": typeof SettingsHostRoute;
  "/settings/keybindings": typeof SettingsKeybindingsRoute;
  "/settings/providers": typeof SettingsProvidersRoute;
  "/settings/service": typeof SettingsServiceRoute;
  "/settings/shell": typeof SettingsShellRoute;
  "/settings/worktrees": typeof SettingsWorktreesRoute;
  "/epics/": typeof EpicsIndexRoute;
  "/settings/": typeof SettingsIndexRoute;
  "/epics/$epicId/$tabId": typeof EpicsEpicIdTabIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/epics"
    | "/onboarding"
    | "/settings"
    | "/draft/$draftId"
    | "/draft/new"
    | "/settings/appearance"
    | "/settings/general"
    | "/settings/host"
    | "/settings/keybindings"
    | "/settings/providers"
    | "/settings/service"
    | "/settings/shell"
    | "/settings/worktrees"
    | "/epics/"
    | "/settings/"
    | "/epics/$epicId/$tabId";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/onboarding"
    | "/draft/$draftId"
    | "/draft/new"
    | "/settings/appearance"
    | "/settings/general"
    | "/settings/host"
    | "/settings/keybindings"
    | "/settings/providers"
    | "/settings/service"
    | "/settings/shell"
    | "/settings/worktrees"
    | "/epics"
    | "/settings"
    | "/epics/$epicId/$tabId";
  id:
    | "__root__"
    | "/"
    | "/epics"
    | "/onboarding"
    | "/settings"
    | "/draft/$draftId"
    | "/draft/new"
    | "/settings/appearance"
    | "/settings/general"
    | "/settings/host"
    | "/settings/keybindings"
    | "/settings/providers"
    | "/settings/service"
    | "/settings/shell"
    | "/settings/worktrees"
    | "/epics/"
    | "/settings/"
    | "/epics/$epicId/$tabId";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  EpicsRoute: typeof EpicsRouteWithChildren;
  OnboardingRoute: typeof OnboardingRoute;
  SettingsRoute: typeof SettingsRouteWithChildren;
  DraftDraftIdRoute: typeof DraftDraftIdRoute;
  DraftNewRoute: typeof DraftNewRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/settings": {
      id: "/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof SettingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/onboarding": {
      id: "/onboarding";
      path: "/onboarding";
      fullPath: "/onboarding";
      preLoaderRoute: typeof OnboardingRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/epics": {
      id: "/epics";
      path: "/epics";
      fullPath: "/epics";
      preLoaderRoute: typeof EpicsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings/": {
      id: "/settings/";
      path: "/";
      fullPath: "/settings/";
      preLoaderRoute: typeof SettingsIndexRouteImport;
      parentRoute: typeof SettingsRoute;
    };
    "/epics/": {
      id: "/epics/";
      path: "/";
      fullPath: "/epics/";
      preLoaderRoute: typeof EpicsIndexRouteImport;
      parentRoute: typeof EpicsRoute;
    };
    "/settings/worktrees": {
      id: "/settings/worktrees";
      path: "/worktrees";
      fullPath: "/settings/worktrees";
      preLoaderRoute: typeof SettingsWorktreesRouteImport;
      parentRoute: typeof SettingsRoute;
    };
    "/settings/shell": {
      id: "/settings/shell";
      path: "/shell";
      fullPath: "/settings/shell";
      preLoaderRoute: typeof SettingsShellRouteImport;
      parentRoute: typeof SettingsRoute;
    };
    "/settings/service": {
      id: "/settings/service";
      path: "/service";
      fullPath: "/settings/service";
      preLoaderRoute: typeof SettingsServiceRouteImport;
      parentRoute: typeof SettingsRoute;
    };
    "/settings/providers": {
      id: "/settings/providers";
      path: "/providers";
      fullPath: "/settings/providers";
      preLoaderRoute: typeof SettingsProvidersRouteImport;
      parentRoute: typeof SettingsRoute;
    };
    "/settings/keybindings": {
      id: "/settings/keybindings";
      path: "/keybindings";
      fullPath: "/settings/keybindings";
      preLoaderRoute: typeof SettingsKeybindingsRouteImport;
      parentRoute: typeof SettingsRoute;
    };
    "/settings/host": {
      id: "/settings/host";
      path: "/host";
      fullPath: "/settings/host";
      preLoaderRoute: typeof SettingsHostRouteImport;
      parentRoute: typeof SettingsRoute;
    };
    "/settings/general": {
      id: "/settings/general";
      path: "/general";
      fullPath: "/settings/general";
      preLoaderRoute: typeof SettingsGeneralRouteImport;
      parentRoute: typeof SettingsRoute;
    };
    "/settings/appearance": {
      id: "/settings/appearance";
      path: "/appearance";
      fullPath: "/settings/appearance";
      preLoaderRoute: typeof SettingsAppearanceRouteImport;
      parentRoute: typeof SettingsRoute;
    };
    "/draft/new": {
      id: "/draft/new";
      path: "/draft/new";
      fullPath: "/draft/new";
      preLoaderRoute: typeof DraftNewRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/draft/$draftId": {
      id: "/draft/$draftId";
      path: "/draft/$draftId";
      fullPath: "/draft/$draftId";
      preLoaderRoute: typeof DraftDraftIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/epics/$epicId/$tabId": {
      id: "/epics/$epicId/$tabId";
      path: "/$epicId/$tabId";
      fullPath: "/epics/$epicId/$tabId";
      preLoaderRoute: typeof EpicsEpicIdTabIdRouteImport;
      parentRoute: typeof EpicsRoute;
    };
  }
}

interface EpicsRouteChildren {
  EpicsIndexRoute: typeof EpicsIndexRoute;
  EpicsEpicIdTabIdRoute: typeof EpicsEpicIdTabIdRoute;
}

const EpicsRouteChildren: EpicsRouteChildren = {
  EpicsIndexRoute: EpicsIndexRoute,
  EpicsEpicIdTabIdRoute: EpicsEpicIdTabIdRoute,
};

const EpicsRouteWithChildren = EpicsRoute._addFileChildren(EpicsRouteChildren);

interface SettingsRouteChildren {
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute;
  SettingsGeneralRoute: typeof SettingsGeneralRoute;
  SettingsHostRoute: typeof SettingsHostRoute;
  SettingsKeybindingsRoute: typeof SettingsKeybindingsRoute;
  SettingsProvidersRoute: typeof SettingsProvidersRoute;
  SettingsServiceRoute: typeof SettingsServiceRoute;
  SettingsShellRoute: typeof SettingsShellRoute;
  SettingsWorktreesRoute: typeof SettingsWorktreesRoute;
  SettingsIndexRoute: typeof SettingsIndexRoute;
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsHostRoute: SettingsHostRoute,
  SettingsKeybindingsRoute: SettingsKeybindingsRoute,
  SettingsProvidersRoute: SettingsProvidersRoute,
  SettingsServiceRoute: SettingsServiceRoute,
  SettingsShellRoute: SettingsShellRoute,
  SettingsWorktreesRoute: SettingsWorktreesRoute,
  SettingsIndexRoute: SettingsIndexRoute,
};

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EpicsRoute: EpicsRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  SettingsRoute: SettingsRouteWithChildren,
  DraftDraftIdRoute: DraftDraftIdRoute,
  DraftNewRoute: DraftNewRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
