export type {
  BrowserAnnotationAttachedIpcEvent,
  BrowserAnnotationAttachPayload,
  BrowserAnnotationAttachRequest,
  BrowserAnnotationAttachResultInput,
  BrowserAnnotationCounts,
  BrowserAnnotationCssRect,
  BrowserAnnotationEndReason,
  BrowserAnnotationForwardedSessionEvent,
  BrowserAnnotationMarkKind,
  BrowserAnnotationMarkSnapshot,
  BrowserAnnotationMode,
  BrowserAnnotationSessionEvent,
  BrowserAnnotationSessionIpcEvent,
  BrowserAnnotationSetTargetChatLabelInput,
  BrowserAnnotationStartFailureReason,
  BrowserAnnotationStartResult,
  BrowserAnnotationTargetOption,
} from "@traycer-clients/shared/platform/browser-annotation";
