import {
  alwaysAvailable,
  isPushPermissionGroupAvailable,
  isSystemNotificationsGroupAvailable,
} from "@/lib/settings/settings-availability";
import { defineSettingsSection } from "@/lib/settings-search/settings-definitions";

export const APP_NOTIFICATIONS = defineSettingsSection("app-notifications", {
  page: {
    label: "Sounds",
    description: "How this app alerts you across hosts.",
    keywords: [
      "notifications",
      "alerts",
      "banner",
      "push",
      "sound",
      "chime",
      "audio",
      "beep",
      "volume",
      "mute",
      "ding",
    ],
  },
  // The chime card shows no heading — the page already names it — so it is not
  // a destination of its own; it and its rows fold into the page.
  chimes: {
    kind: "group",
    search: { contributesTo: "page" },
    label: "Chimes",
    description: null,
    breadcrumb: null,
    availableWhen: alwaysAvailable,
    keywords: [],
  },
  chimeNeedsAction: {
    kind: "row",
    group: "chimes",
    search: { contributesTo: "page" },
    label: "Needs action",
    description: "Approvals and interviews.",
    availableWhen: alwaysAvailable,
    keywords: [],
  },
  chimeFailure: {
    kind: "row",
    group: "chimes",
    search: { contributesTo: "page" },
    label: "Failure",
    description: "Errored turns, stalls, crashes, and rate limits.",
    availableWhen: alwaysAvailable,
    keywords: [],
  },
  chimeDone: {
    kind: "row",
    group: "chimes",
    search: { contributesTo: "page" },
    label: "Done",
    description: "Completed or intentionally stopped turns.",
    availableWhen: alwaysAvailable,
    keywords: [],
  },
  chimeInfo: {
    kind: "row",
    group: "chimes",
    search: { contributesTo: "page" },
    label: "Info",
    description:
      "Sharing, comments, access changes, and other informational notifications.",
    availableWhen: alwaysAvailable,
    keywords: [],
  },
  events: {
    kind: "group",
    search: { anchor: "app-notifications-events" },
    label: "Events",
    description: null,
    breadcrumb: null,
    availableWhen: alwaysAvailable,
    keywords: ["alerts", "triggers", "when"],
  },
  notificationEvents: {
    kind: "row",
    group: "events",
    search: { anchor: "app-notification-events" },
    label: "Notification events",
    description:
      "Choose which events alert you for the host selected in Settings.",
    availableWhen: alwaysAvailable,
    keywords: ["events", "turn done", "alerts", "filter", "which"],
  },
  system: {
    kind: "group",
    search: { anchor: "app-notifications-system" },
    label: "System",
    description: null,
    breadcrumb: null,
    availableWhen: isSystemNotificationsGroupAvailable,
    keywords: ["os", "native", "banner", "badge"],
  },
  osNotifications: {
    kind: "row",
    group: "system",
    search: { anchor: "app-notifications-os" },
    label: "OS notifications",
    description:
      "Banners, badges, and delivery are managed by your operating system.",
    availableWhen: alwaysAvailable,
    keywords: ["os", "native", "banner", "badge", "macos", "windows"],
  },
  thisPhone: {
    kind: "group",
    search: { anchor: "app-notifications-this-phone" },
    label: "This phone",
    description: null,
    breadcrumb: null,
    availableWhen: isPushPermissionGroupAvailable,
    keywords: ["mobile", "ios", "android", "device", "push"],
  },
  pushNotifications: {
    kind: "row",
    group: "thisPhone",
    search: { anchor: "app-notifications-push" },
    label: "Push notifications",
    // The sentence reports the OS permission state, so it is the row's status.
    description: null,
    availableWhen: alwaysAvailable,
    keywords: ["push", "mobile", "phone", "permission", "remote"],
  },
});
