import {
  alwaysAvailable,
  isZoomRowAvailable,
} from "@/lib/settings/settings-availability";
import { defineSettingsSection } from "@/lib/settings-search/settings-definitions";

export const APPEARANCE = defineSettingsSection("appearance", {
  page: {
    label: "Appearance",
    description: "Themes, fonts, and display preferences.",
    keywords: [
      "look",
      "style",
      "visual",
      "ui",
      // Controls without search anchors land on the Appearance page.
      "theme",
      "dark mode",
      "light mode",
      "color scheme",
      "theme mode",
      "follow device",
      "background opacity",
      "palette",
      "preset",
      "gruvbox",
      "nord",
      "tokyo night",
      "everforest",
      "github",
      "prompt font",
      "ligatures",
      "panel animations",
      "contrast",
    ],
  },
  themes: {
    kind: "group",
    search: { anchor: "appearance-themes" },
    label: "Themes",
    description: null,
    breadcrumb: null,
    availableWhen: alwaysAvailable,
    keywords: ["palette", "preset", "color scheme"],
  },
  themeMode: {
    kind: "row",
    group: "themes",
    search: { anchor: "appearance-theme-mode" },
    label: "Theme mode",
    description:
      "Choose separate light and dark themes below. Follow device switches between them with your device’s appearance.",
    availableWhen: alwaysAvailable,
    keywords: ["follow device", "system", "appearance"],
  },
  lightTheme: {
    kind: "row",
    group: "themes",
    search: { anchor: "appearance-light-theme" },
    label: "Light theme",
    description: null,
    availableWhen: alwaysAvailable,
    keywords: ["palette", "preset"],
  },
  darkTheme: {
    kind: "row",
    group: "themes",
    search: { anchor: "appearance-dark-theme" },
    label: "Dark theme",
    description: null,
    availableWhen: alwaysAvailable,
    keywords: ["palette", "preset"],
  },
  backgroundOpacity: {
    kind: "row",
    group: "themes",
    search: { anchor: "appearance-background-opacity" },
    label: "Background opacity",
    description:
      "Opacity of menu, dialog, and prompt backgrounds. Lower values let more show through; 100% is solid.",
    availableWhen: alwaysAvailable,
    keywords: ["transparency", "translucent", "glass", "blur"],
  },
  startPage: {
    kind: "group",
    search: { anchor: "appearance-start-page" },
    label: "Start page",
    description: null,
    breadcrumb: null,
    availableWhen: alwaysAvailable,
    keywords: ["home", "landing", "backdrop"],
  },
  wallpaper: {
    kind: "row",
    group: "startPage",
    search: { anchor: "appearance-wallpaper" },
    label: "Wallpaper",
    // The chosen image's name is live copy, rendered as the row's status.
    description: null,
    availableWhen: alwaysAvailable,
    keywords: ["background image", "backdrop", "photo"],
  },
  // The effect rows exist only once a wallpaper is chosen, and each only for
  // the effects it adjusts.
  wallpaperEffect: {
    kind: "row",
    group: "startPage",
    search: { contributesTo: "page" },
    label: "Wallpaper effect",
    description:
      "Keep the original photo, turn it into a dot pattern, or add film grain.",
    availableWhen: alwaysAvailable,
    keywords: [],
  },
  effectStrength: {
    kind: "row",
    group: "startPage",
    search: { contributesTo: "page" },
    label: "Effect strength",
    description: "Adjust how strongly the effect changes the photo.",
    availableWhen: alwaysAvailable,
    keywords: [],
  },
  tintWallpaper: {
    kind: "row",
    group: "startPage",
    search: { contributesTo: "page" },
    label: "Tint wallpaper with theme accent color",
    description: null,
    availableWhen: alwaysAvailable,
    keywords: [],
  },
  showGreeting: {
    kind: "row",
    group: "startPage",
    search: { anchor: "appearance-show-greeting" },
    label: "Show greeting",
    description: null,
    availableWhen: alwaysAvailable,
    keywords: ["welcome", "hello", "home"],
  },
  showRecentTasks: {
    kind: "row",
    group: "startPage",
    search: { anchor: "appearance-show-recent-tasks" },
    label: "Show recent tasks",
    description: null,
    availableWhen: alwaysAvailable,
    keywords: ["history", "recent history", "home"],
  },
  interface: {
    kind: "group",
    search: { anchor: "appearance-interface" },
    label: "Interface",
    description: null,
    breadcrumb: null,
    availableWhen: alwaysAvailable,
    keywords: ["layout", "chrome", "controls"],
  },
  zoom: {
    kind: "row",
    group: "interface",
    search: { anchor: "appearance-zoom" },
    label: "Zoom",
    description: "Scales the whole app; font sizes only adjust typography.",
    availableWhen: isZoomRowAvailable,
    keywords: ["scale", "size", "bigger", "smaller", "magnify", "display"],
  },
  pointerCursors: {
    kind: "row",
    group: "interface",
    search: { anchor: "appearance-pointer-cursors" },
    label: "Show a hand cursor over clickable controls",
    description:
      "Use a hand cursor over buttons, links, and other clickable controls.",
    availableWhen: alwaysAvailable,
    keywords: ["cursor", "mouse", "hand", "hover"],
  },
  minimapSide: {
    kind: "row",
    group: "interface",
    search: { anchor: "appearance-minimap-side" },
    label: "Minimap position",
    description:
      "Minimaps are compact overviews for navigating chats and artifacts. Choose where they appear, or hide them.",
    availableWhen: alwaysAvailable,
    keywords: ["minimap", "side", "overview", "left", "right", "hide"],
  },
  typography: {
    kind: "group",
    search: { anchor: "appearance-typography" },
    label: "Fonts and text",
    description: null,
    breadcrumb: null,
    availableWhen: alwaysAvailable,
    keywords: ["font", "text", "size", "typeface", "typography"],
  },
  uiFont: {
    kind: "row",
    group: "typography",
    search: { anchor: "appearance-ui-font" },
    label: "Interface font",
    description: "Font and size used across the Traycer interface.",
    availableWhen: alwaysAvailable,
    keywords: ["font", "typeface", "text size", "interface"],
  },
  codeFont: {
    kind: "row",
    group: "typography",
    search: { anchor: "appearance-code-font" },
    label: "Code font",
    description: "Font and size used for code blocks and diffs.",
    availableWhen: alwaysAvailable,
    keywords: ["font", "monospace", "mono", "diff", "editor"],
  },
  promptFont: {
    kind: "row",
    group: "typography",
    search: { anchor: "appearance-prompt-font" },
    label: "Prompt font",
    description: "The font used where you write prompts.",
    availableWhen: alwaysAvailable,
    keywords: ["composer", "input", "typeface"],
  },
  fontLigatures: {
    kind: "row",
    group: "typography",
    search: { anchor: "appearance-font-ligatures" },
    label: "Use font ligatures",
    description:
      "Join characters such as != into a single symbol in prompts and code, when supported by the font. The underlying text stays the same.",
    availableWhen: alwaysAvailable,
    keywords: ["glyphs", "symbols", "arrows"],
  },
  motionAndReadability: {
    kind: "group",
    search: { anchor: "appearance-motion-readability" },
    label: "Motion and readability",
    description: null,
    breadcrumb: null,
    availableWhen: alwaysAvailable,
    keywords: ["animation", "accessibility", "reduce motion"],
  },
  panelAnimations: {
    kind: "row",
    group: "motionAndReadability",
    search: { anchor: "appearance-panel-animations" },
    label: "Panel animations",
    description: "Animate sidebars, menus, and dialogs as they open and close.",
    availableWhen: alwaysAvailable,
    keywords: ["motion", "transitions", "reduce motion"],
  },
  panelAnimationDuration: {
    kind: "row",
    group: "motionAndReadability",
    search: { anchor: "appearance-animation-duration" },
    label: "Animation duration",
    description:
      "Lower values are faster; 0 ms is instant. Applies when panel animations are on.",
    availableWhen: alwaysAvailable,
    keywords: ["speed", "motion", "transition"],
  },
  contrast: {
    kind: "row",
    group: "motionAndReadability",
    search: { anchor: "appearance-contrast" },
    label: "Text and border contrast",
    description:
      "100% uses the theme’s original colors. Increase it to make text and borders stand out more.",
    availableWhen: alwaysAvailable,
    keywords: ["accessibility", "readability", "legibility"],
  },
  terminal: {
    kind: "group",
    search: { anchor: "appearance-terminal-group" },
    label: "Terminal",
    description: null,
    breadcrumb: null,
    availableWhen: alwaysAvailable,
    keywords: ["shell", "console", "xterm"],
  },
  terminalFont: {
    kind: "row",
    group: "terminal",
    search: { anchor: "appearance-terminal-font" },
    label: "Terminal font",
    description:
      "Font and size used in the terminal. Follows the code font until you set them.",
    availableWhen: alwaysAvailable,
    keywords: ["font", "monospace", "mono", "console", "xterm"],
  },
  terminalCursor: {
    kind: "row",
    group: "terminal",
    search: { anchor: "appearance-terminal-cursor" },
    label: "Terminal cursor",
    description: "Shape of the cursor in the terminal.",
    availableWhen: alwaysAvailable,
    keywords: ["cursor", "block", "bar", "underline", "caret"],
  },
  blinkCursor: {
    kind: "row",
    group: "terminal",
    search: { anchor: "appearance-blink-cursor" },
    label: "Blink cursor",
    description: "Blink the terminal cursor while the terminal is focused.",
    availableWhen: alwaysAvailable,
    keywords: ["blink", "flash", "cursor", "caret"],
  },
  // Its OWN group rather than a row under Interface: the groups here are
  // either a cross-cutting appearance concern (Themes, Interface, Fonts and
  // text, Motion and readability, Icon colors) or one surface's own settings
  // (Start page, Terminal), and this is the second kind. Interface is app-wide
  // chrome - zoom, the pointer cursor, where minimaps sit - and a default that
  // only an epic's comm-graph tile reads would be misfiled there.
  agentOffice: {
    kind: "group",
    search: { anchor: "appearance-agent-office" },
    label: "Agent office",
    description: null,
    breadcrumb: null,
    availableWhen: alwaysAvailable,
    keywords: ["office", "agents", "comm graph", "epic canvas", "tile"],
  },
  agentOfficeDefaultView: {
    kind: "row",
    group: "agentOffice",
    search: { anchor: "appearance-agent-office-default-view" },
    label: "Default view",
    description:
      "For epics you have not chosen a view in. Auto picks by how much fits the tile.",
    availableWhen: alwaysAvailable,
    // The view NAMES are deliberately not listed: they come from the office
    // view registry, and a second copy here would drift from it the moment a
    // view is added or renamed. "Auto" is the choice, not a view.
    keywords: ["office", "view", "auto", "floor", "layout", "default"],
  },
  artifactIcons: {
    kind: "group",
    search: { anchor: "appearance-artifact-icons" },
    label: "Icon colors",
    description: null,
    breadcrumb: null,
    availableWhen: alwaysAvailable,
    keywords: ["icons", "artifacts", "files", "color"],
  },
  artifactIconColors: {
    kind: "row",
    group: "artifactIcons",
    search: { anchor: "appearance-artifact-icon-colors" },
    label: "Color icons by type",
    description:
      "Give chats, agents, terminals, and artifacts distinct icon colors. Turn off to use neutral icons.",
    availableWhen: alwaysAvailable,
    keywords: ["icons", "color", "file type", "monochrome", "neutral"],
  },
});
