import { alwaysAvailable } from "@/lib/settings/settings-availability";
import { defineSettingsSection } from "@/lib/settings-search/settings-definitions";

// No host-scoped section indexes an anchor: every card on this page is dropped
// or concealed for an unresolved, connecting or vanished host, so only the
// page itself is a stable destination. Every card and row here folds into it.
export const HOST_OVERVIEW = defineSettingsSection("host", {
  page: {
    label: "Overview",
    description: "The selected host's status, version, and installation.",
    keywords: [
      "host",
      "status",
      "version",
      "update",
      "upgrade",
      "restart",
      "service",
      "machine",
      "server",
      "connection",
      "rename",
      "installation",
      "install",
      "path",
      "binary",
      "data & migration",
      "import your work",
      "import",
      "migration",
      "migrate",
      "transfer",
      "cloud",
      "danger zone",
      "remove",
      "uninstall",
      "remove traycer",
      "delete",
      "deregister",
      "remove from account",
      "unlink",
      "file edit snapshots",
      "snapshots",
      "undo",
      "disk space",
      "cache",
    ],
  },
  versionHistory: {
    kind: "group",
    search: { contributesTo: "page" },
    label: "Version history",
    description: null,
    breadcrumb: null,
    availableWhen: alwaysAvailable,
    keywords: [],
  },
  captureVersions: {
    kind: "row",
    group: "versionHistory",
    search: { contributesTo: "page" },
    label: "Capture versions",
    description: "Save restorable observations of artifact edits on this host.",
    availableWhen: alwaysAvailable,
    keywords: [],
  },
  retention: {
    kind: "row",
    group: "versionHistory",
    search: { contributesTo: "page" },
    label: "Retention",
    description: "History is pruned when any per-artifact limit is reached.",
    availableWhen: alwaysAvailable,
    keywords: [],
  },
  storage: {
    kind: "row",
    group: "versionHistory",
    search: { contributesTo: "page" },
    label: "Storage",
    description:
      "Referenced history is retained; reclaimable bytes can be cleared now.",
    availableWhen: alwaysAvailable,
    keywords: [],
  },
  clearVersionHistory: {
    kind: "row",
    group: "versionHistory",
    search: { contributesTo: "page" },
    label: "Clear version history",
    description:
      "Remove all version-history records from this host; only unreferenced content bytes are reclaimed.",
    availableWhen: alwaysAvailable,
    keywords: [],
  },
  dataAndMigration: {
    kind: "group",
    search: { contributesTo: "page" },
    label: "Data & migration",
    description: null,
    breadcrumb: null,
    availableWhen: alwaysAvailable,
    keywords: [],
  },
  importYourWork: {
    kind: "row",
    group: "dataAndMigration",
    search: { contributesTo: "page" },
    label: "Import your work",
    // Switches to live progress while an import runs, so it is a status.
    description: null,
    availableWhen: alwaysAvailable,
    keywords: [],
  },
  dataMigration: {
    kind: "row",
    group: "dataAndMigration",
    search: { contributesTo: "page" },
    label: "Data migration",
    // Switches to live progress while a migration runs, so it is a status.
    description: null,
    availableWhen: alwaysAvailable,
    keywords: [],
  },
  installation: {
    kind: "group",
    search: { contributesTo: "page" },
    label: "Installation",
    description: null,
    breadcrumb: null,
    availableWhen: alwaysAvailable,
    keywords: [],
  },
  dangerZone: {
    kind: "group",
    search: { contributesTo: "page" },
    label: "Danger zone",
    description: null,
    breadcrumb: null,
    availableWhen: alwaysAvailable,
    keywords: [],
  },
  fileEditSnapshots: {
    kind: "row",
    group: "dangerZone",
    search: { contributesTo: "page" },
    label: "File edit snapshots",
    // Names the host it is about, so it is a status.
    description: null,
    availableWhen: alwaysAvailable,
    keywords: [],
  },
  removeFromAccount: {
    kind: "row",
    group: "dangerZone",
    search: { contributesTo: "page" },
    label: "Remove from account",
    // Names the host it is about, so it is a status.
    description: null,
    availableWhen: alwaysAvailable,
    keywords: [],
  },
  removeTraycer: {
    kind: "row",
    group: "dangerZone",
    search: { contributesTo: "page" },
    label: "Remove Traycer from this computer",
    description:
      "Stops the background host and services and removes the installed components. Your agents and history are preserved, and the host won't reinstall itself.",
    availableWhen: alwaysAvailable,
    keywords: [],
  },
  removalIncomplete: {
    kind: "row",
    group: "dangerZone",
    search: { contributesTo: "page" },
    label: "Traycer removal incomplete",
    description:
      "The background service is still registered. Traycer has not been fully removed; try again before quitting the app.",
    availableWhen: alwaysAvailable,
    keywords: [],
  },
  removalUnverified: {
    kind: "row",
    group: "dangerZone",
    search: { contributesTo: "page" },
    label: "Traycer removal unverified",
    description:
      "The removal commands finished, but Traycer could not verify whether the background service remains registered. Run traycer host service status in a terminal and resolve any remaining service before quitting the app.",
    availableWhen: alwaysAvailable,
    keywords: [],
  },
  removed: {
    kind: "row",
    group: "dangerZone",
    search: { contributesTo: "page" },
    label: "Traycer removed",
    description:
      "Background components were removed. Your agents, history and credentials are preserved on this computer. To finish, quit Traycer and drag it from Applications to the Trash.",
    availableWhen: alwaysAvailable,
    keywords: [],
  },
});
