import { alwaysAvailable } from "@/lib/settings/settings-availability";
import { defineSettingsSection } from "@/lib/settings-search/settings-definitions";

// Per-category rows contribute to their parent search target because they
// only render when per-type placement is enabled.
export const OPENING_BEHAVIOR = defineSettingsSection("opening-behavior", {
  page: {
    availableWhen: alwaysAvailable,
    label: "Opening behavior",
    description: "Where links and tiles land when you open them.",
    keywords: ["open", "click", "navigate", "placement", "target"],
  },
  links: {
    kind: "group",
    search: { anchor: "opening-links" },
    label: "Links",
    description: null,
    breadcrumb: null,
    availableWhen: alwaysAvailable,
    keywords: ["url", "hyperlink", "external", "browser"],
  },
  openLinks: {
    kind: "row",
    group: "links",
    search: { anchor: "opening-links-default" },
    label: "Open links",
    description: null,
    availableWhen: alwaysAvailable,
    keywords: [
      "url",
      "external",
      "in app",
      "default browser",
      "per kind",
      "markdown",
      "terminal",
      "github",
      "pull request",
      "images",
      "lightbox",
    ],
  },
  linkMarkdown: {
    kind: "row",
    group: "links",
    search: { contributesTo: "openLinks" },
    label: "Markdown",
    description: "In chat, artifacts, comm graph, and markdown previews.",
    availableWhen: alwaysAvailable,
    keywords: [],
  },
  linkTerminal: {
    kind: "row",
    group: "links",
    search: { contributesTo: "openLinks" },
    label: "Terminal",
    description: "URLs and hyperlinks printed by a terminal.",
    availableWhen: alwaysAvailable,
    keywords: [],
  },
  linkGithub: {
    kind: "row",
    group: "links",
    search: { contributesTo: "openLinks" },
    label: "GitHub",
    description: "Pull request rows, headers, commits, and worktree PR chips.",
    availableWhen: alwaysAvailable,
    keywords: [],
  },
  linkImages: {
    kind: "row",
    group: "links",
    search: { contributesTo: "openLinks" },
    label: "Images",
    description: "Images opened from the lightbox.",
    availableWhen: alwaysAvailable,
    keywords: [],
  },
  tilePlacement: {
    kind: "group",
    search: { anchor: "opening-tile-placement" },
    label: "Tile placement",
    description: null,
    breadcrumb: null,
    availableWhen: alwaysAvailable,
    keywords: ["split", "pane", "layout", "window", "tab"],
  },
  openNewTiles: {
    kind: "row",
    group: "tilePlacement",
    search: { anchor: "opening-tiles-default" },
    label: "Open new tiles",
    // Only a narrow window has a sentence for this row, and it is a status.
    description: null,
    availableWhen: alwaysAvailable,
    keywords: [
      "split",
      "pane",
      "replace",
      "new tab",
      "layout",
      "per category",
      "files",
      "diffs",
      "artifacts",
      "agents",
      "terminals",
    ],
  },
  tileContent: {
    kind: "row",
    group: "tilePlacement",
    search: { contributesTo: "openNewTiles" },
    label: "Files, diffs & artifacts",
    description:
      "Files, diffs, pull requests, artifacts, command output, and the communication graph.",
    availableWhen: alwaysAvailable,
    keywords: [],
  },
  tileConversation: {
    kind: "row",
    group: "tilePlacement",
    search: { contributesTo: "openNewTiles" },
    label: "Agents & terminals",
    description: "Chats, agents, and terminal sessions.",
    availableWhen: alwaysAvailable,
    keywords: [],
  },
  tileSideChat: {
    kind: "row",
    group: "tilePlacement",
    search: { contributesTo: "openNewTiles" },
    label: "Side chats",
    description:
      "Asides started with /btw or /side, placed next to the chat they were asked from.",
    availableWhen: alwaysAvailable,
    keywords: [],
  },
});
