// AUTO-GENERATED by protocol/scripts/compat/snapshot-frozen-catalog-lines.ts - do not edit by hand.
// Frozen catalog response schemas for the three id-carrying methods. The
// companion test fails if a frozen export drifts from this snapshot.
export const FROZEN_CATALOG_LINE_SNAPSHOTS = {
  "formatVersion": 1,
  "fixtures": {
    "agent.gui.listHarnesses@1.0": {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "type": "object",
      "properties": {
        "harnesses": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "id": {
                "type": "string",
                "enum": [
                  "claude",
                  "codex",
                  "opencode",
                  "traycer",
                  "cursor"
                ]
              },
              "label": {
                "type": "string"
              },
              "available": {
                "type": "boolean"
              },
              "error": {
                "anyOf": [
                  {
                    "type": "string"
                  },
                  {
                    "type": "null"
                  }
                ]
              },
              "modes": {
                "type": "array",
                "items": {
                  "type": "string",
                  "enum": [
                    "gui",
                    "tui"
                  ]
                }
              },
              "requiresApiKey": {
                "type": "boolean"
              },
              "supportedPermissionModes": {
                "default": [
                  "supervised",
                  "auto_accept_edits",
                  "full_access"
                ],
                "type": "array",
                "items": {
                  "type": "string",
                  "enum": [
                    "supervised",
                    "auto_accept_edits",
                    "full_access"
                  ]
                }
              }
            },
            "required": [
              "id",
              "label",
              "available",
              "error",
              "modes",
              "requiresApiKey",
              "supportedPermissionModes"
            ],
            "additionalProperties": false
          }
        }
      },
      "required": [
        "harnesses"
      ],
      "additionalProperties": false
    },
    "agent.gui.listHarnesses@2.0": {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "type": "object",
      "properties": {
        "harnesses": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "id": {
                "type": "string",
                "enum": [
                  "claude",
                  "codex",
                  "opencode",
                  "traycer",
                  "cursor",
                  "grok",
                  "qwen",
                  "kiro",
                  "droid",
                  "kimi",
                  "copilot",
                  "kilocode",
                  "openrouter"
                ]
              },
              "label": {
                "type": "string"
              },
              "available": {
                "type": "boolean"
              },
              "error": {
                "anyOf": [
                  {
                    "type": "string"
                  },
                  {
                    "type": "null"
                  }
                ]
              },
              "modes": {
                "type": "array",
                "items": {
                  "type": "string",
                  "enum": [
                    "gui",
                    "tui"
                  ]
                }
              },
              "requiresApiKey": {
                "type": "boolean"
              },
              "supportedPermissionModes": {
                "default": [
                  "supervised",
                  "auto_accept_edits",
                  "full_access"
                ],
                "type": "array",
                "items": {
                  "type": "string",
                  "enum": [
                    "supervised",
                    "auto_accept_edits",
                    "full_access"
                  ]
                }
              },
              "availabilityPending": {
                "default": false,
                "type": "boolean"
              }
            },
            "required": [
              "id",
              "label",
              "available",
              "error",
              "modes",
              "requiresApiKey",
              "supportedPermissionModes",
              "availabilityPending"
            ],
            "additionalProperties": false
          }
        }
      },
      "required": [
        "harnesses"
      ],
      "additionalProperties": false
    },
    "agent.list@1.0": {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "type": "object",
      "properties": {
        "caller": {
          "type": "object",
          "properties": {
            "agentId": {
              "type": "string"
            },
            "canSendMessages": {
              "type": "boolean"
            }
          },
          "required": [
            "agentId",
            "canSendMessages"
          ],
          "additionalProperties": false
        },
        "scope": {
          "type": "string",
          "enum": [
            "user",
            "all"
          ]
        },
        "agents": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "id": {
                "type": "string"
              },
              "parentId": {
                "anyOf": [
                  {
                    "type": "string"
                  },
                  {
                    "type": "null"
                  }
                ]
              },
              "hostId": {
                "type": "string"
              },
              "isLocal": {
                "type": "boolean"
              },
              "surface": {
                "type": "string",
                "enum": [
                  "gui",
                  "tui"
                ]
              },
              "harnessId": {
                "anyOf": [
                  {
                    "type": "string",
                    "enum": [
                      "claude",
                      "codex",
                      "opencode",
                      "traycer",
                      "cursor"
                    ]
                  },
                  {
                    "type": "null"
                  }
                ]
              },
              "isSelf": {
                "type": "boolean"
              },
              "title": {
                "anyOf": [
                  {
                    "type": "string"
                  },
                  {
                    "type": "null"
                  }
                ]
              },
              "capabilities": {
                "type": "object",
                "properties": {
                  "readTranscript": {
                    "type": "boolean"
                  },
                  "sendMessage": {
                    "type": "boolean"
                  }
                },
                "required": [
                  "readTranscript",
                  "sendMessage"
                ],
                "additionalProperties": false
              },
              "active": {
                "type": "boolean"
              },
              "folderPaths": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              "isWorktree": {
                "type": "boolean"
              }
            },
            "required": [
              "id",
              "parentId",
              "hostId",
              "isLocal",
              "surface",
              "harnessId",
              "isSelf",
              "title",
              "capabilities",
              "active",
              "folderPaths",
              "isWorktree"
            ],
            "additionalProperties": false
          }
        }
      },
      "required": [
        "caller",
        "scope",
        "agents"
      ],
      "additionalProperties": false
    },
    "agent.list@2.0": {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "type": "object",
      "properties": {
        "caller": {
          "type": "object",
          "properties": {
            "agentId": {
              "type": "string"
            },
            "canSendMessages": {
              "type": "boolean"
            }
          },
          "required": [
            "agentId",
            "canSendMessages"
          ],
          "additionalProperties": false
        },
        "scope": {
          "type": "string",
          "enum": [
            "user",
            "all"
          ]
        },
        "agents": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "id": {
                "type": "string"
              },
              "parentId": {
                "anyOf": [
                  {
                    "type": "string"
                  },
                  {
                    "type": "null"
                  }
                ]
              },
              "hostId": {
                "type": "string"
              },
              "isLocal": {
                "type": "boolean"
              },
              "surface": {
                "type": "string",
                "enum": [
                  "gui",
                  "tui"
                ]
              },
              "harnessId": {
                "anyOf": [
                  {
                    "type": "string",
                    "enum": [
                      "claude",
                      "codex",
                      "opencode",
                      "traycer",
                      "cursor",
                      "grok",
                      "qwen",
                      "kiro",
                      "droid",
                      "kimi",
                      "copilot",
                      "kilocode",
                      "openrouter"
                    ]
                  },
                  {
                    "type": "null"
                  }
                ]
              },
              "isSelf": {
                "type": "boolean"
              },
              "title": {
                "anyOf": [
                  {
                    "type": "string"
                  },
                  {
                    "type": "null"
                  }
                ]
              },
              "capabilities": {
                "type": "object",
                "properties": {
                  "readTranscript": {
                    "type": "boolean"
                  },
                  "sendMessage": {
                    "type": "boolean"
                  }
                },
                "required": [
                  "readTranscript",
                  "sendMessage"
                ],
                "additionalProperties": false
              },
              "active": {
                "type": "boolean"
              },
              "folderPaths": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              "isWorktree": {
                "type": "boolean"
              }
            },
            "required": [
              "id",
              "parentId",
              "hostId",
              "isLocal",
              "surface",
              "harnessId",
              "isSelf",
              "title",
              "capabilities",
              "active",
              "folderPaths",
              "isWorktree"
            ],
            "additionalProperties": false
          }
        }
      },
      "required": [
        "caller",
        "scope",
        "agents"
      ],
      "additionalProperties": false
    },
    "providers.list@1.0": {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "type": "object",
      "properties": {
        "providers": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "providerId": {
                "type": "string",
                "enum": [
                  "claude-code",
                  "codex",
                  "opencode",
                  "cursor",
                  "traycer"
                ]
              },
              "enabled": {
                "type": "boolean"
              },
              "disabledBy": {
                "anyOf": [
                  {
                    "type": "object",
                    "properties": {
                      "userId": {
                        "type": "string"
                      },
                      "handle": {
                        "anyOf": [
                          {
                            "type": "string"
                          },
                          {
                            "type": "null"
                          }
                        ]
                      },
                      "at": {
                        "type": "number"
                      }
                    },
                    "required": [
                      "userId",
                      "handle",
                      "at"
                    ],
                    "additionalProperties": false
                  },
                  {
                    "type": "null"
                  }
                ]
              },
              "selected": {
                "oneOf": [
                  {
                    "type": "object",
                    "properties": {
                      "kind": {
                        "type": "string",
                        "const": "bundled"
                      }
                    },
                    "required": [
                      "kind"
                    ],
                    "additionalProperties": false
                  },
                  {
                    "type": "object",
                    "properties": {
                      "kind": {
                        "type": "string",
                        "const": "path"
                      }
                    },
                    "required": [
                      "kind"
                    ],
                    "additionalProperties": false
                  },
                  {
                    "type": "object",
                    "properties": {
                      "kind": {
                        "type": "string",
                        "const": "custom"
                      },
                      "path": {
                        "type": "string"
                      }
                    },
                    "required": [
                      "kind",
                      "path"
                    ],
                    "additionalProperties": false
                  }
                ]
              },
              "candidates": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "kind": {
                      "type": "string",
                      "enum": [
                        "bundled",
                        "path",
                        "custom"
                      ]
                    },
                    "path": {
                      "type": "string"
                    },
                    "version": {
                      "anyOf": [
                        {
                          "type": "string"
                        },
                        {
                          "type": "null"
                        }
                      ]
                    },
                    "available": {
                      "type": "boolean"
                    },
                    "versionPending": {
                      "type": "boolean"
                    }
                  },
                  "required": [
                    "kind",
                    "path",
                    "version",
                    "available",
                    "versionPending"
                  ],
                  "additionalProperties": false
                }
              },
              "authPending": {
                "type": "boolean"
              },
              "checkedAt": {
                "anyOf": [
                  {
                    "type": "number"
                  },
                  {
                    "type": "null"
                  }
                ]
              },
              "apiKey": {
                "type": "object",
                "properties": {
                  "supported": {
                    "type": "boolean"
                  },
                  "configured": {
                    "type": "boolean"
                  },
                  "source": {
                    "anyOf": [
                      {
                        "type": "string",
                        "enum": [
                          "stored",
                          "env"
                        ]
                      },
                      {
                        "type": "null"
                      }
                    ]
                  }
                },
                "required": [
                  "supported",
                  "configured",
                  "source"
                ],
                "additionalProperties": false
              },
              "terminalAgentArgs": {
                "default": "",
                "type": "string"
              },
              "envOverrides": {
                "default": [],
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "key": {
                      "type": "string"
                    },
                    "value": {
                      "anyOf": [
                        {
                          "type": "string"
                        },
                        {
                          "type": "null"
                        }
                      ]
                    }
                  },
                  "required": [
                    "key",
                    "value"
                  ],
                  "additionalProperties": false
                }
              },
              "loginCapability": {
                "default": null,
                "anyOf": [
                  {
                    "type": "object",
                    "properties": {
                      "oauthArgs": {
                        "anyOf": [
                          {
                            "type": "array",
                            "items": {
                              "type": "string"
                            }
                          },
                          {
                            "type": "null"
                          }
                        ]
                      },
                      "token": {
                        "anyOf": [
                          {
                            "type": "object",
                            "properties": {
                              "vars": {
                                "type": "array",
                                "items": {
                                  "type": "string"
                                }
                              }
                            },
                            "required": [
                              "vars"
                            ],
                            "additionalProperties": false
                          },
                          {
                            "type": "null"
                          }
                        ]
                      }
                    },
                    "required": [
                      "oauthArgs",
                      "token"
                    ],
                    "additionalProperties": false
                  },
                  {
                    "type": "null"
                  }
                ]
              },
              "auth": {
                "type": "object",
                "properties": {
                  "status": {
                    "type": "string",
                    "enum": [
                      "authenticated",
                      "unauthenticated",
                      "unknown"
                    ]
                  },
                  "badgeText": {
                    "anyOf": [
                      {
                        "type": "string"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "label": {
                    "anyOf": [
                      {
                        "type": "string"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "detail": {
                    "anyOf": [
                      {
                        "type": "string"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  }
                },
                "required": [
                  "status",
                  "badgeText",
                  "label",
                  "detail"
                ],
                "additionalProperties": false
              }
            },
            "required": [
              "providerId",
              "enabled",
              "disabledBy",
              "selected",
              "candidates",
              "authPending",
              "checkedAt",
              "apiKey",
              "terminalAgentArgs",
              "envOverrides",
              "loginCapability",
              "auth"
            ],
            "additionalProperties": false
          }
        }
      },
      "required": [
        "providers"
      ],
      "additionalProperties": false
    },
    "providers.list@2.0": {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "type": "object",
      "properties": {
        "providers": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "providerId": {
                "type": "string",
                "enum": [
                  "claude-code",
                  "codex",
                  "opencode",
                  "cursor",
                  "traycer",
                  "grok",
                  "qwen",
                  "kiro",
                  "droid",
                  "kimi",
                  "copilot",
                  "kilocode",
                  "openrouter"
                ]
              },
              "enabled": {
                "type": "boolean"
              },
              "disabledBy": {
                "anyOf": [
                  {
                    "type": "object",
                    "properties": {
                      "userId": {
                        "type": "string"
                      },
                      "handle": {
                        "anyOf": [
                          {
                            "type": "string"
                          },
                          {
                            "type": "null"
                          }
                        ]
                      },
                      "at": {
                        "type": "number"
                      }
                    },
                    "required": [
                      "userId",
                      "handle",
                      "at"
                    ],
                    "additionalProperties": false
                  },
                  {
                    "type": "null"
                  }
                ]
              },
              "selected": {
                "oneOf": [
                  {
                    "type": "object",
                    "properties": {
                      "kind": {
                        "type": "string",
                        "const": "bundled"
                      }
                    },
                    "required": [
                      "kind"
                    ],
                    "additionalProperties": false
                  },
                  {
                    "type": "object",
                    "properties": {
                      "kind": {
                        "type": "string",
                        "const": "path"
                      }
                    },
                    "required": [
                      "kind"
                    ],
                    "additionalProperties": false
                  },
                  {
                    "type": "object",
                    "properties": {
                      "kind": {
                        "type": "string",
                        "const": "custom"
                      },
                      "path": {
                        "type": "string"
                      }
                    },
                    "required": [
                      "kind",
                      "path"
                    ],
                    "additionalProperties": false
                  }
                ]
              },
              "candidates": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "kind": {
                      "type": "string",
                      "enum": [
                        "bundled",
                        "path",
                        "custom"
                      ]
                    },
                    "path": {
                      "type": "string"
                    },
                    "version": {
                      "anyOf": [
                        {
                          "type": "string"
                        },
                        {
                          "type": "null"
                        }
                      ]
                    },
                    "available": {
                      "type": "boolean"
                    },
                    "versionPending": {
                      "type": "boolean"
                    }
                  },
                  "required": [
                    "kind",
                    "path",
                    "version",
                    "available",
                    "versionPending"
                  ],
                  "additionalProperties": false
                }
              },
              "authPending": {
                "type": "boolean"
              },
              "checkedAt": {
                "anyOf": [
                  {
                    "type": "number"
                  },
                  {
                    "type": "null"
                  }
                ]
              },
              "apiKey": {
                "type": "object",
                "properties": {
                  "supported": {
                    "type": "boolean"
                  },
                  "configured": {
                    "type": "boolean"
                  },
                  "source": {
                    "anyOf": [
                      {
                        "type": "string",
                        "enum": [
                          "stored",
                          "env"
                        ]
                      },
                      {
                        "type": "null"
                      }
                    ]
                  }
                },
                "required": [
                  "supported",
                  "configured",
                  "source"
                ],
                "additionalProperties": false
              },
              "terminalAgentArgs": {
                "default": "",
                "type": "string"
              },
              "envOverrides": {
                "default": [],
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "key": {
                      "type": "string"
                    },
                    "value": {
                      "anyOf": [
                        {
                          "type": "string"
                        },
                        {
                          "type": "null"
                        }
                      ]
                    }
                  },
                  "required": [
                    "key",
                    "value"
                  ],
                  "additionalProperties": false
                }
              },
              "loginCapability": {
                "default": null,
                "anyOf": [
                  {
                    "type": "object",
                    "properties": {
                      "oauthArgs": {
                        "anyOf": [
                          {
                            "type": "array",
                            "items": {
                              "type": "string"
                            }
                          },
                          {
                            "type": "null"
                          }
                        ]
                      },
                      "token": {
                        "anyOf": [
                          {
                            "type": "object",
                            "properties": {
                              "vars": {
                                "type": "array",
                                "items": {
                                  "type": "string"
                                }
                              }
                            },
                            "required": [
                              "vars"
                            ],
                            "additionalProperties": false
                          },
                          {
                            "type": "null"
                          }
                        ]
                      }
                    },
                    "required": [
                      "oauthArgs",
                      "token"
                    ],
                    "additionalProperties": false
                  },
                  {
                    "type": "null"
                  }
                ]
              },
              "availabilityPending": {
                "default": false,
                "type": "boolean"
              },
              "auth": {
                "type": "object",
                "properties": {
                  "status": {
                    "type": "string",
                    "enum": [
                      "authenticated",
                      "unauthenticated",
                      "configured",
                      "unavailable",
                      "unknown"
                    ]
                  },
                  "badgeText": {
                    "anyOf": [
                      {
                        "type": "string"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "label": {
                    "anyOf": [
                      {
                        "type": "string"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "detail": {
                    "anyOf": [
                      {
                        "type": "string"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  }
                },
                "required": [
                  "status",
                  "badgeText",
                  "label",
                  "detail"
                ],
                "additionalProperties": false
              }
            },
            "required": [
              "providerId",
              "enabled",
              "disabledBy",
              "selected",
              "candidates",
              "authPending",
              "checkedAt",
              "apiKey",
              "terminalAgentArgs",
              "envOverrides",
              "loginCapability",
              "availabilityPending",
              "auth"
            ],
            "additionalProperties": false
          }
        }
      },
      "required": [
        "providers"
      ],
      "additionalProperties": false
    },
    "providers.list@3.0": {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "type": "object",
      "properties": {
        "providers": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "providerId": {
                "type": "string",
                "enum": [
                  "claude-code",
                  "codex",
                  "opencode",
                  "cursor",
                  "traycer",
                  "grok",
                  "qwen",
                  "kiro",
                  "droid",
                  "kimi",
                  "copilot",
                  "kilocode",
                  "openrouter",
                  "amp"
                ]
              },
              "enabled": {
                "type": "boolean"
              },
              "disabledBy": {
                "anyOf": [
                  {
                    "type": "object",
                    "properties": {
                      "userId": {
                        "type": "string"
                      },
                      "handle": {
                        "anyOf": [
                          {
                            "type": "string"
                          },
                          {
                            "type": "null"
                          }
                        ]
                      },
                      "at": {
                        "type": "number"
                      }
                    },
                    "required": [
                      "userId",
                      "handle",
                      "at"
                    ],
                    "additionalProperties": false
                  },
                  {
                    "type": "null"
                  }
                ]
              },
              "selected": {
                "oneOf": [
                  {
                    "type": "object",
                    "properties": {
                      "kind": {
                        "type": "string",
                        "const": "bundled"
                      }
                    },
                    "required": [
                      "kind"
                    ],
                    "additionalProperties": false
                  },
                  {
                    "type": "object",
                    "properties": {
                      "kind": {
                        "type": "string",
                        "const": "path"
                      }
                    },
                    "required": [
                      "kind"
                    ],
                    "additionalProperties": false
                  },
                  {
                    "type": "object",
                    "properties": {
                      "kind": {
                        "type": "string",
                        "const": "custom"
                      },
                      "path": {
                        "type": "string"
                      }
                    },
                    "required": [
                      "kind",
                      "path"
                    ],
                    "additionalProperties": false
                  }
                ]
              },
              "candidates": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "kind": {
                      "type": "string",
                      "enum": [
                        "bundled",
                        "path",
                        "custom"
                      ]
                    },
                    "path": {
                      "type": "string"
                    },
                    "version": {
                      "anyOf": [
                        {
                          "type": "string"
                        },
                        {
                          "type": "null"
                        }
                      ]
                    },
                    "available": {
                      "type": "boolean"
                    },
                    "versionPending": {
                      "type": "boolean"
                    }
                  },
                  "required": [
                    "kind",
                    "path",
                    "version",
                    "available",
                    "versionPending"
                  ],
                  "additionalProperties": false
                }
              },
              "authPending": {
                "type": "boolean"
              },
              "checkedAt": {
                "anyOf": [
                  {
                    "type": "number"
                  },
                  {
                    "type": "null"
                  }
                ]
              },
              "apiKey": {
                "type": "object",
                "properties": {
                  "supported": {
                    "type": "boolean"
                  },
                  "configured": {
                    "type": "boolean"
                  },
                  "source": {
                    "anyOf": [
                      {
                        "type": "string",
                        "enum": [
                          "stored",
                          "env"
                        ]
                      },
                      {
                        "type": "null"
                      }
                    ]
                  }
                },
                "required": [
                  "supported",
                  "configured",
                  "source"
                ],
                "additionalProperties": false
              },
              "terminalAgentArgs": {
                "default": "",
                "type": "string"
              },
              "envOverrides": {
                "default": [],
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "key": {
                      "type": "string"
                    },
                    "value": {
                      "anyOf": [
                        {
                          "type": "string"
                        },
                        {
                          "type": "null"
                        }
                      ]
                    }
                  },
                  "required": [
                    "key",
                    "value"
                  ],
                  "additionalProperties": false
                }
              },
              "loginCapability": {
                "default": null,
                "anyOf": [
                  {
                    "type": "object",
                    "properties": {
                      "oauthArgs": {
                        "anyOf": [
                          {
                            "type": "array",
                            "items": {
                              "type": "string"
                            }
                          },
                          {
                            "type": "null"
                          }
                        ]
                      },
                      "token": {
                        "anyOf": [
                          {
                            "type": "object",
                            "properties": {
                              "vars": {
                                "type": "array",
                                "items": {
                                  "type": "string"
                                }
                              }
                            },
                            "required": [
                              "vars"
                            ],
                            "additionalProperties": false
                          },
                          {
                            "type": "null"
                          }
                        ]
                      }
                    },
                    "required": [
                      "oauthArgs",
                      "token"
                    ],
                    "additionalProperties": false
                  },
                  {
                    "type": "null"
                  }
                ]
              },
              "availabilityPending": {
                "default": false,
                "type": "boolean"
              },
              "auth": {
                "type": "object",
                "properties": {
                  "status": {
                    "type": "string",
                    "enum": [
                      "authenticated",
                      "unauthenticated",
                      "configured",
                      "unavailable",
                      "unknown"
                    ]
                  },
                  "badgeText": {
                    "anyOf": [
                      {
                        "type": "string"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "label": {
                    "anyOf": [
                      {
                        "type": "string"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "detail": {
                    "anyOf": [
                      {
                        "type": "string"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  }
                },
                "required": [
                  "status",
                  "badgeText",
                  "label",
                  "detail"
                ],
                "additionalProperties": false
              }
            },
            "required": [
              "providerId",
              "enabled",
              "disabledBy",
              "selected",
              "candidates",
              "authPending",
              "checkedAt",
              "apiKey",
              "terminalAgentArgs",
              "envOverrides",
              "loginCapability",
              "availabilityPending",
              "auth"
            ],
            "additionalProperties": false
          }
        }
      },
      "required": [
        "providers"
      ],
      "additionalProperties": false
    }
  }
} as const;
