import type { ConnectionManifest } from "@traycer/protocol/framework/index";

/**
 * One historically-released, still-supported app/host version's frozen `ConnectionManifest` - the per-method `{ major, minor }` canonical it advertised at that version - plus a human-readable label.
 */
export type SupportMatrixEntry = {
  readonly version: string;
  readonly manifest: ConnectionManifest;
};

/**
 * AUTO-GENERATED entries come from `protocol/scripts/snapshot-support-matrix.ts`.
 * Do not hand-edit an entry's `manifest` - regenerate it instead.
 */
export const supportMatrix: readonly SupportMatrixEntry[] = [
  {
    version: "host-v1.0.0",
    manifest: {
      "agent.create": { major: 1, minor: 0 },
      "agent.getTranscript": { major: 1, minor: 0 },
      "agent.gui.getPlan": { major: 1, minor: 0 },
      "agent.gui.listCommands": { major: 1, minor: 0 },
      "agent.gui.listHarnesses": { major: 2, minor: 0 },
      "agent.gui.listModels": { major: 1, minor: 0 },
      "agent.inbox.read": { major: 1, minor: 0 },
      "agent.list": { major: 2, minor: 0 },
      "agent.listHarnessModels": { major: 1, minor: 0 },
      "agent.selectionGuide": { major: 1, minor: 0 },
      "agent.selectionGuide.getGlobal": { major: 1, minor: 0 },
      "agent.selectionGuide.getGlobalOnboardingDraft": { major: 1, minor: 0 },
      "agent.selectionGuide.resetGlobalToDefault": { major: 1, minor: 0 },
      "agent.selectionGuide.setGlobal": { major: 1, minor: 0 },
      "agent.sendMessage": { major: 1, minor: 0 },
      "agent.stop": { major: 1, minor: 0 },
      "agent.tui.generateTitle": { major: 1, minor: 0 },
      "agent.tui.listHarnesses": { major: 1, minor: 0 },
      "agent.tui.prepareLaunch": { major: 1, minor: 0 },
      "agent.tui.recordActivity": { major: 1, minor: 0 },
      "agent.tui.turnEnded": { major: 1, minor: 0 },
      "comments.listThreads": { major: 1, minor: 0 },
      "comments.setThreadStatus": { major: 1, minor: 0 },
      "editor.openPaths": { major: 1, minor: 0 },
      "epic.batchDelete": { major: 1, minor: 0 },
      "epic.batchUpdateRoles": { major: 1, minor: 0 },
      "epic.create": { major: 1, minor: 0 },
      "epic.createArtifact": { major: 1, minor: 0 },
      "epic.createChat": { major: 1, minor: 0 },
      "epic.createCommentThread": { major: 1, minor: 0 },
      "epic.createTuiAgent": { major: 1, minor: 0 },
      "epic.deleteArtifact": { major: 1, minor: 0 },
      "epic.deleteChat": { major: 1, minor: 0 },
      "epic.deleteComment": { major: 1, minor: 0 },
      "epic.deleteCommentThread": { major: 1, minor: 0 },
      "epic.deleteTuiAgent": { major: 1, minor: 0 },
      "epic.editComment": { major: 1, minor: 0 },
      "epic.grantAccess": { major: 1, minor: 0 },
      "epic.listCollaborators": { major: 1, minor: 0 },
      "epic.listCommentThreads": { major: 1, minor: 0 },
      "epic.listTasks": { major: 1, minor: 0 },
      "epic.mentionEpics": { major: 1, minor: 0 },
      "epic.mentionReviews": { major: 1, minor: 0 },
      "epic.mentionSpecs": { major: 1, minor: 0 },
      "epic.mentionStories": { major: 1, minor: 0 },
      "epic.mentionTickets": { major: 1, minor: 0 },
      "epic.removeRepo": { major: 1, minor: 0 },
      "epic.renameArtifact": { major: 1, minor: 0 },
      "epic.renameChat": { major: 1, minor: 0 },
      "epic.renameTuiAgent": { major: 1, minor: 0 },
      "epic.reparentArtifact": { major: 1, minor: 0 },
      "epic.reparentChat": { major: 1, minor: 0 },
      "epic.replyToCommentThread": { major: 1, minor: 0 },
      "epic.resolveArtifactByPath": { major: 1, minor: 0 },
      "epic.revokeCollaborator": { major: 1, minor: 0 },
      "epic.setCommentThreadResolved": { major: 1, minor: 0 },
      "epic.updateArtifactStatus": { major: 1, minor: 0 },
      "epic.updateTitle": { major: 1, minor: 0 },
      "git.getCapabilities": { major: 1, minor: 0 },
      "git.getFileDiff": { major: 1, minor: 0 },
      "git.getFileDiffs": { major: 1, minor: 0 },
      "git.listChangedFiles": { major: 1, minor: 0 },
      "host.getRateLimitUsage": { major: 1, minor: 1 },
      "host.getRuntimeCapabilities": { major: 1, minor: 0 },
      "host.status": { major: 1, minor: 0 },
      "phase.migrateToEpic": { major: 1, minor: 0 },
      "providers.addCustomPath": { major: 1, minor: 0 },
      "providers.awaitLogin": { major: 1, minor: 0 },
      "providers.cancelLogin": { major: 1, minor: 0 },
      "providers.clearApiKey": { major: 1, minor: 0 },
      "providers.deleteEnvOverride": { major: 1, minor: 0 },
      "providers.detectVersion": { major: 1, minor: 0 },
      "providers.list": { major: 2, minor: 0 },
      "providers.removeCustomPath": { major: 1, minor: 0 },
      "providers.setApiKey": { major: 1, minor: 0 },
      "providers.setEnabled": { major: 1, minor: 0 },
      "providers.setEnvOverride": { major: 1, minor: 0 },
      "providers.setSelection": { major: 1, minor: 0 },
      "providers.setTerminalAgentArgs": { major: 1, minor: 0 },
      "providers.startLogin": { major: 1, minor: 0 },
      "snapshots.clearLocalSnapshots": { major: 1, minor: 0 },
      "snapshots.getLocalStorageSize": { major: 1, minor: 0 },
      "snapshots.readSnapshotDiff": { major: 1, minor: 0 },
      "speech.ensureModel": { major: 1, minor: 0 },
      "speech.getModelStatus": { major: 1, minor: 0 },
      "terminal.create": { major: 1, minor: 0 },
      "terminal.kill": { major: 1, minor: 0 },
      "terminal.list": { major: 1, minor: 0 },
      "terminal.rename": { major: 1, minor: 0 },
      "workspace.listDirectory": { major: 1, minor: 0 },
      "workspace.listFileTree": { major: 1, minor: 0 },
      "workspace.mentionFiles": { major: 1, minor: 0 },
      "workspace.mentionFolders": { major: 1, minor: 0 },
      "workspace.mentionGitBranches": { major: 1, minor: 0 },
      "workspace.mentionGitCommits": { major: 1, minor: 0 },
      "workspace.mentionGitRoot": { major: 1, minor: 0 },
      "workspace.mentionWorktrees": { major: 1, minor: 0 },
      "workspace.prepareFolders": { major: 1, minor: 0 },
      "workspace.readFile": { major: 1, minor: 0 },
      "workspace.resolvePathsByRepoIdentifiers": { major: 1, minor: 0 },
      "workspaceBinding.removeEntry": { major: 1, minor: 0 },
      "worktree.create": { major: 1, minor: 0 },
      "worktree.createPaths": { major: 1, minor: 0 },
      "worktree.delete": { major: 1, minor: 0 },
      "worktree.getBinding": { major: 1, minor: 0 },
      "worktree.import": { major: 1, minor: 0 },
      "worktree.listAllForHost": { major: 1, minor: 0 },
      "worktree.listBindingsForEpic": { major: 1, minor: 0 },
      "worktree.listBranches": { major: 1, minor: 0 },
      "worktree.listByWorkspacePaths": { major: 1, minor: 1 },
      "worktree.retrySetup": { major: 1, minor: 0 },
      "worktree.setEntryMode": { major: 1, minor: 0 },
      "worktree.setRepoScripts": { major: 1, minor: 0 },
    },
  },
];
