/**
 * Snapshot frozen catalog response schemas for the three id-carrying methods.
 *
 *   bun run protocol/scripts/compat/snapshot-frozen-catalog-lines.ts > \
 *     protocol/src/host/__tests__/__fixtures__/frozen-catalog-lines.ts
 *
 * The companion test fails if a frozen export drifts from this snapshot.
 * When a new frozen line lands (e.g. V30 with Amp), add it here and re-run.
 */
import { z } from "zod";
import {
  listAgentsResponseSchemaV10,
  listAgentsResponseSchemaV20,
} from "../../src/host/agent/shared";
import {
  listGuiHarnessesResponseSchemaV10,
  listGuiHarnessesResponseSchemaV20,
} from "../../src/host/agent/gui/unary-schemas";
import {
  providersListResponseSchemaV10,
  providersListResponseSchemaV20,
} from "../../src/host/provider-schemas";

function dump(schema: z.ZodType): unknown {
  return z.toJSONSchema(schema, { unrepresentable: "any" });
}

const FIXTURES = {
  "agent.gui.listHarnesses@1.0": dump(listGuiHarnessesResponseSchemaV10),
  "agent.gui.listHarnesses@2.0": dump(listGuiHarnessesResponseSchemaV20),
  "agent.list@1.0": dump(listAgentsResponseSchemaV10),
  "agent.list@2.0": dump(listAgentsResponseSchemaV20),
  "providers.list@1.0": dump(providersListResponseSchemaV10),
  "providers.list@2.0": dump(providersListResponseSchemaV20),
};

const HEADER =
  "// AUTO-GENERATED by protocol/scripts/compat/snapshot-frozen-catalog-lines.ts - do not edit by hand.\n" +
  "// Frozen catalog response schemas for the three id-carrying methods. The\n" +
  "// companion test fails if a frozen export drifts from this snapshot.\n";

process.stdout.write(
  `${HEADER}export const FROZEN_CATALOG_LINE_SNAPSHOTS = ${JSON.stringify(
    { formatVersion: 1, fixtures: FIXTURES },
    null,
    2,
  )} as const;\n`,
);
