/**
 * Payload-only module for provider-native MCP / plugins / skills settings.
 * RPC contracts for these verbs were folded onto released carriers
 * (`providers.list@3.1`, `providers.setEnabled@2.1`, login family minors).
 * Re-export the carrier payload schemas from here for host/gui consumers.
 */
export {
  DEFAULT_PROVIDER_NATIVE_CAPABILITIES,
  nativeAuthActionSchema,
  nativeAuthCancelContextSchema,
  nativeAuthPollContextSchema,
  nativeAuthResultSchema,
  nativeListQuerySchema,
  nativeListResultSchema,
  nativeMutationResultSchema,
  nativeMutationSchema,
  providerMcpAuthActionSchema,
  providerMcpAuthReadSchema,
  providerMcpAuthTypeSchema,
  providerMcpAuthWriteSchema,
  providerMcpCapabilitiesSchema,
  providerMcpCapabilityActionSchema,
  providerMcpDataSourceSchema,
  providerMcpMutationActionSchema,
  providerMcpPerToolBackingSchema,
  providerMcpSecretMaskSchema,
  providerMcpSecretWriteSchema,
  providerMcpServerSchema,
  providerMcpServerStatusSchema,
  providerMcpServerTransportReadSchema,
  providerMcpServerTransportWriteSchema,
  providerMcpToolSchema,
  providerMcpTransportSchema,
  providerMcpWritePathSchema,
  providerNativeCapabilitiesSchema,
  providerNativeErrorCodeSchema,
  providerNativeErrorResultSchema,
  providerNativeScopeSchema,
  providerNativeScopeTupleBaseSchema,
  providerNativeScopeTupleSchema,
  providerPluginSchema,
  providerPluginsAddModeSchema,
  providerPluginsCapabilitiesSchema,
  providerPluginsCapabilityActionSchema,
  providerSettingsTabSchema,
  providerSkillSchema,
  providerSkillSourceBadgeSchema,
  providerSkillsCapabilitiesSchema,
  providerSkillsCapabilityActionSchema,
  providersMcpMutateActionSchema,
  providersPluginsMutateActionSchema,
  providersSkillsMutateActionSchema,
  refineProviderNativeScope,
  withProviderNativeScopeInvariant,
  type NativeAuthAction,
  type NativeAuthCancelContext,
  type NativeAuthPollContext,
  type NativeAuthResult,
  type NativeListQuery,
  type NativeListResult,
  type NativeMutation,
  type NativeMutationResult,
  type ProviderMcpAuthAction,
  type ProviderMcpAuthRead,
  type ProviderMcpAuthType,
  type ProviderMcpAuthWrite,
  type ProviderMcpCapabilities,
  type ProviderMcpCapabilityAction,
  type ProviderMcpDataSource,
  type ProviderMcpMutationAction,
  type ProviderMcpPerToolBacking,
  type ProviderMcpSecretMask,
  type ProviderMcpSecretWrite,
  type ProviderMcpServer,
  type ProviderMcpServerStatus,
  type ProviderMcpServerTransportRead,
  type ProviderMcpServerTransportWrite,
  type ProviderMcpTool,
  type ProviderMcpTransport,
  type ProviderMcpWritePath,
  type ProviderNativeCapabilities,
  type ProviderNativeErrorCode,
  type ProviderNativeErrorResult,
  type ProviderNativeScope,
  type ProviderNativeScopeTuple,
  type ProviderPlugin,
  type ProviderPluginsAddMode,
  type ProviderPluginsCapabilities,
  type ProviderPluginsCapabilityAction,
  type ProviderSettingsTab,
  type ProviderSkill,
  type ProviderSkillSourceBadge,
  type ProviderSkillsCapabilities,
  type ProviderSkillsCapabilityAction,
  type ProvidersMcpMutateAction,
  type ProvidersPluginsMutateAction,
  type ProvidersSkillsMutateAction,
} from "./provider-native-schemas";
