export {
  hostDoctorV10,
  hostGetInstallationInfoV10,
  hostServiceDeregisterV10,
  hostServiceRegisterV10,
  hostServiceStatusV10,
  hostUpdateCheckV10,
  hostUpdateInstallV10,
  hostUpdateInstallV11,
  hostUpdateInstallUpgradeV10ToV11,
} from "./contracts";

export {
  RPC_DOCTOR_TRIVIALLY_GREEN_ISSUE_CODES,
  LOCAL_WS_DOCTOR_TRIVIALLY_GREEN_ISSUE_CODES,
  doctorTriviallyGreenIssueCodesForVantage,
  hostAvailableManifestSchema,
  hostDoctorIssueSchema,
  hostDoctorRequestSchema,
  hostDoctorResponseSchema,
  hostGetInstallationInfoRequestSchema,
  hostGetInstallationInfoResponseSchema,
  hostServiceDeregisterRequestSchema,
  hostServiceDeregisterResponseSchema,
  hostServiceRegisterRequestSchema,
  hostServiceRegisterResponseSchema,
  hostServiceStateSchema,
  hostServiceStatusRequestSchema,
  hostServiceStatusResponseSchema,
  hostUpdateCheckRequestSchema,
  hostUpdateCheckResponseSchema,
  hostUpdateInstallRequestSchema,
  hostUpdateInstallResponseSchema,
  type HostAvailableManifest,
  type HostDoctorIssue,
  type DoctorTransportVantage,
  type HostDoctorRequest,
  type HostDoctorResponse,
  type HostGetInstallationInfoRequest,
  type HostGetInstallationInfoResponse,
  type HostServiceDeregisterRequest,
  type HostServiceDeregisterResponse,
  type HostServiceRegisterRequest,
  type HostServiceRegisterResponse,
  type HostServiceState,
  type HostServiceStatusRequest,
  type HostServiceStatusResponse,
  type HostUpdateCheckRequest,
  type HostUpdateCheckResponse,
  type HostUpdateInstallRequest,
  type HostUpdateInstallResponse,
} from "./schemas";
