export const NOTIFICATION_EVENT_TYPES = {
  INVITED: "invited",
  ROLE_CHANGED: "roleChanged",
  REVOKED: "revoked",
  THREAD_CREATED: "threadCreated",
  COMMENT_ADDED: "commentAdded",
  THREAD_RESOLVED: "threadResolved",
  THREAD_DELETED: "threadDeleted",
} as const;

export interface InvitedEvent {
  kind: typeof NOTIFICATION_EVENT_TYPES.INVITED;
  epicId: string;
  actorName: string;
}

export interface RoleChangedEvent {
  kind: typeof NOTIFICATION_EVENT_TYPES.ROLE_CHANGED;
  epicId: string;
  actorName: string;
  newRole: string;
}

export interface RevokedEvent {
  kind: typeof NOTIFICATION_EVENT_TYPES.REVOKED;
  epicId: string;
  actorName: string;
}

/** Shared base shape for all comment-related notification events. */
export interface CommentEventBase {
  epicId: string;
  artifactType: "spec" | "ticket" | "story" | "review";
  artifactId: string;
  threadId: string;
  actorName: string;
}

export interface ThreadCreatedEvent extends CommentEventBase {
  kind: typeof NOTIFICATION_EVENT_TYPES.THREAD_CREATED;
}

export interface CommentAddedEvent extends CommentEventBase {
  kind: typeof NOTIFICATION_EVENT_TYPES.COMMENT_ADDED;
}

export interface ThreadResolvedEvent extends CommentEventBase {
  kind: typeof NOTIFICATION_EVENT_TYPES.THREAD_RESOLVED;
}

export interface ThreadDeletedEvent extends CommentEventBase {
  kind: typeof NOTIFICATION_EVENT_TYPES.THREAD_DELETED;
}

/** Discriminated union of all notification event variants. */
export type NotificationEvent =
  | InvitedEvent
  | RoleChangedEvent
  | RevokedEvent
  | ThreadCreatedEvent
  | CommentAddedEvent
  | ThreadResolvedEvent
  | ThreadDeletedEvent;

/** Union of comment-related notification events. */
export type CommentNotificationEvent =
  | ThreadCreatedEvent
  | CommentAddedEvent
  | ThreadResolvedEvent
  | ThreadDeletedEvent;

/**
 * Represents a single notification entry stored in a user's notification room.
 * Entries are stored as Y.Map values inside a Y.Array in the room's Y.Doc.
 */
export interface NotificationEntry {
  /** Unique notification ID (ULID, generated by server). */
  id: string;

  /** Unix timestamp in milliseconds when the notification was created. */
  createdAt: number;

  /** Null = unread. Set to epoch ms when the user reads the notification. */
  readAt: number | null;

  /** The structured notification event (discriminated union). */
  event: NotificationEvent;
}
